[package]
name = "ingestor-kafka-hdfs"
version = "2.5.0"
description = "Solana block ingestor service"
authors = ["Aurimas Narkevicius <aurimas.n@dexterlab.com>"]
license = "AGPL-3"
repository = "https://github.com/dexterlaboss/ingestor-kafka-hdfs"
homepage = "https://dexterlab.com"
edition = "2021"

[dependencies]
bytes = "1.2"
clap = "2.33.1"
log = "0.4.17"
env_logger = "0.9.0"
envy = "0.4.2"
prost = "0.11.0"
prost-types = "0.11.1"
serde = "1.0.144"
serde_derive = "1.0.103"
#serde_json = "1.0.83"
serde_json = { version = "1.0.83", features = ["float_roundtrip"] }
borsh = "0.9.1"
borsh-derive = "0.9.1"
bs58 = "0.4.0"
base64 = "0.13.0"
console = "0.15.0"
pretty-hex = "0.3.0"
futures = "0.3.24"
#hdrs = "0.1.4"
thiserror = "1.0"
dotenv = "0.15.0"
bincode = "1.3.3"
hbase-thrift = "=1.1.0"
thrift = "0.15.0"
thrift-pool = "=1.4.0"
#hdfs = "0.0.4"
#chrono = { version = "0.4.22", features = ["serde"] }
backoff = { version = "0.4.0", features = ["tokio"] }
#solana-binary-encoder = "=1.2.2"
solana-block-decoder = "=2.1.2"
solana-storage-utils = "=2.1.2"
solana-transaction-status = "=2.2.0"
solana-clap-utils = "=2.2.1"
solana-sdk = "=2.2.1"
solana-hash = "=2.2.1"
solana-storage-proto = "=2.2.0"
dexter-storage-proto-tx = "=2.1.2"
solana-version = "=2.2.1"
rust_decimal = "1.0"
hex = "0.4.3"
md5 = "0.7"
memcache = "0.17.2"
#opendal = { version = "0.36.0", default-features = false, features = ["services-hdfs"] }
anyhow = "1.0"
xxhash-rust = { version = "0.8.12", features = ["xxh3", "xxh32"] }



#flate2 = "1.0"
#fs-hdfs3 = "0.1.12"

async-compression = { version = "0.4.18", features = ["tokio", "gzip"] }
tokio-util = { version = "0.7", features = ["io"] }
hdfs-native = "0.11"
async-trait = "0.1"

#redis = { version = "0.25", features = ["tokio-comp"] }

[dependencies.tokio]
features = ["rt-multi-thread", "macros", "io-util"]
version = "1.11.0"

[dependencies.rdkafka]
features = ["cmake-build", "gssapi", "ssl", "sasl", "tokio"]
version = "0.29.0"
# git = "https://github.com/fede1024/rust-rdkafka"
# rev = "65520c820565f9882475cc29cd6d149940515324"

[[bin]]
name = "ingestor-kafka-hbase"
path = "src/main.rs"

[build-dependencies]
rustc_version = "0.4"
