FROM rust:1.83-slim-bullseye AS build

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    software-properties-common \
    cmake \
    build-essential \
    wget \
    libclang-dev \
    libudev-dev \
    libssl-dev \
    libsasl2-dev \
    pkg-config \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*